using System.Text.Json.Serialization;
using SuperChat.Contracts.Features.WorkItems;

namespace SuperChat.Contracts.Features.Chat;

[JsonPolymorphic(TypeDiscriminatorPropertyName = "modelType")]
[JsonDerivedType(typeof(GenericChatResultItemViewModel), "generic")]
[JsonDerivedType(typeof(RequestChatResultItemViewModel), "request")]
[JsonDerivedType(typeof(EventChatResultItemViewModel), "event")]
[JsonDerivedType(typeof(ActionItemChatResultItemViewModel), "actionItem")]
public record ChatResultItemViewModel(
    Guid? Id,
    string Title,
    string Summary,
    string SourceRoom,
    DateTimeOffset? Timestamp,
    WorkItemType? Type = null,
    WorkItemStatus? Status = null,
    WorkItemPriority? Priority = null,
    WorkItemOwner? Owner = null,
    WorkItemOrigin? Origin = null,
    AiReviewState? ReviewState = null,
    DateTimeOffset? PlannedAt = null,
    DateTimeOffset? DueAt = null,
    WorkItemSource? Source = null,
    DateTimeOffset? UpdatedAt = null,
    bool IsOverdue = false,
    MeetingJoinProvider? MeetingProvider = null,
    Uri? MeetingJoinUrl = null)
{
    public ChatResultItemViewModel(
        string Title,
        string Summary,
        string SourceRoom,
        DateTimeOffset? Timestamp,
        WorkItemType? Type = null,
        WorkItemStatus? Status = null,
        WorkItemPriority? Priority = null,
        WorkItemOwner? Owner = null,
        WorkItemOrigin? Origin = null,
        AiReviewState? ReviewState = null,
        DateTimeOffset? PlannedAt = null,
        DateTimeOffset? DueAt = null,
        WorkItemSource? Source = null,
        DateTimeOffset? UpdatedAt = null,
        bool IsOverdue = false,
        MeetingJoinProvider? MeetingProvider = null,
        Uri? MeetingJoinUrl = null)
        : this(
            null,
            Title,
            Summary,
            SourceRoom,
            Timestamp,
            Type,
            Status,
            Priority,
            Owner,
            Origin,
            ReviewState,
            PlannedAt,
            DueAt,
            Source,
            UpdatedAt,
            IsOverdue,
            MeetingProvider,
            MeetingJoinUrl)
    {
    }
}

public sealed record GenericChatResultItemViewModel(
    string Title,
    string Summary,
    string SourceRoom,
    DateTimeOffset? Timestamp,
    WorkItemType? Type = null,
    WorkItemStatus? Status = null,
    WorkItemPriority? Priority = null,
    WorkItemOwner? Owner = null,
    WorkItemOrigin? Origin = null,
    AiReviewState? ReviewState = null,
    DateTimeOffset? PlannedAt = null,
    DateTimeOffset? DueAt = null,
    WorkItemSource? Source = null,
    DateTimeOffset? UpdatedAt = null,
    bool IsOverdue = false,
    MeetingJoinProvider? MeetingProvider = null,
    Uri? MeetingJoinUrl = null)
    : ChatResultItemViewModel(
        null,
        Title,
        Summary,
        SourceRoom,
        Timestamp,
        Type,
        Status,
        Priority,
        Owner,
        Origin,
        ReviewState,
        PlannedAt,
        DueAt,
        Source,
        UpdatedAt,
        IsOverdue,
        MeetingProvider,
        MeetingJoinUrl);

public sealed record RequestChatResultItemViewModel(
    string Title,
    string Summary,
    string SourceRoom,
    DateTimeOffset? Timestamp,
    RequestStatus RequestStatus = RequestStatus.AwaitingResponse,
    WorkItemPriority PriorityValue = WorkItemPriority.Normal,
    WorkItemOwner? Owner = null,
    WorkItemOrigin OriginValue = WorkItemOrigin.Request,
    AiReviewState ReviewStateValue = AiReviewState.NeedsReview,
    DateTimeOffset? PlannedAt = null,
    DateTimeOffset? DueAt = null,
    WorkItemSource? Source = null,
    DateTimeOffset? UpdatedAt = null,
    bool IsOverdue = false)
    : ChatResultItemViewModel(
        null,
        Title,
        Summary,
        SourceRoom,
        Timestamp,
        WorkItemType.Request,
        RequestStatus.ToWorkItemStatus(),
        PriorityValue,
        Owner,
        OriginValue,
        ReviewStateValue,
        PlannedAt,
        DueAt,
        Source,
        UpdatedAt,
        IsOverdue);

public sealed record EventChatResultItemViewModel(
    string Title,
    string Summary,
    string SourceRoom,
    DateTimeOffset? Timestamp,
    EventStatus EventStatus = EventStatus.PendingConfirmation,
    WorkItemPriority PriorityValue = WorkItemPriority.Normal,
    WorkItemOwner? Owner = null,
    WorkItemOrigin OriginValue = WorkItemOrigin.DetectedFromChat,
    AiReviewState ReviewStateValue = AiReviewState.NeedsReview,
    DateTimeOffset? PlannedAt = null,
    DateTimeOffset? DueAt = null,
    WorkItemSource? Source = null,
    DateTimeOffset? UpdatedAt = null,
    bool IsOverdue = false,
    MeetingJoinProvider? MeetingProvider = null,
    Uri? MeetingJoinUrl = null)
    : ChatResultItemViewModel(
        null,
        Title,
        Summary,
        SourceRoom,
        Timestamp,
        WorkItemType.Event,
        EventStatus.ToWorkItemStatus(),
        PriorityValue,
        Owner,
        OriginValue,
        ReviewStateValue,
        PlannedAt,
        DueAt,
        Source,
        UpdatedAt,
        IsOverdue,
        MeetingProvider,
        MeetingJoinUrl);

public sealed record ActionItemChatResultItemViewModel(
    string Title,
    string Summary,
    string SourceRoom,
    DateTimeOffset? Timestamp,
    ActionItemStatus ActionItemStatus = ActionItemStatus.ToDo,
    WorkItemPriority PriorityValue = WorkItemPriority.Normal,
    WorkItemOwner? Owner = null,
    WorkItemOrigin OriginValue = WorkItemOrigin.DetectedFromChat,
    AiReviewState ReviewStateValue = AiReviewState.NeedsReview,
    DateTimeOffset? PlannedAt = null,
    DateTimeOffset? DueAt = null,
    WorkItemSource? Source = null,
    DateTimeOffset? UpdatedAt = null,
    bool IsOverdue = false)
    : ChatResultItemViewModel(
        null,
        Title,
        Summary,
        SourceRoom,
        Timestamp,
        WorkItemType.ActionItem,
        ActionItemStatus.ToWorkItemStatus(),
        PriorityValue,
        Owner,
        OriginValue,
        ReviewStateValue,
        PlannedAt,
        DueAt,
        Source,
        UpdatedAt,
        IsOverdue);
