// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SuperChat.Infrastructure.Shared.Persistence;

#nullable disable

namespace SuperChat.Infrastructure.Migrations
{
    [DbContext(typeof(SuperChatDbContext))]
    [Migration("20260428070441_RenameNormalizedMessagesToChatMessages")]
    partial class RenameNormalizedMessagesToChatMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SuperChat.Infrastructure.Shared.Persistence.ApiSessionEntity", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Token");

                    b.HasIndex("UserId");

                    b.ToTable("api_sessions", (string)null);
                });

            modelBuilder.Entity("SuperChat.Infrastructure.Shared.Persistence.AppUserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone_id");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("app_users", (string)null);
                });

            modelBuilder.Entity("SuperChat.Infrastructure.Shared.Persistence.ChatMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChatTitle")
                        .HasColumnType("text")
                        .HasColumnName("chat_title");

                    b.Property<string>("ExternalChatId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_chat_id");

                    b.Property<string>("ExternalMessageId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_message_id");

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean")
                        .HasColumnName("processed");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sender_name");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Processed");

                    b.HasIndex("UserId", "ExternalChatId", "ExternalMessageId")
                        .IsUnique();

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("SuperChat.Infrastructure.Shared.Persistence.ChunkBuildCheckpointEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("LastObservedMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_observed_message_id");

                    b.Property<DateTimeOffset?>("LastObservedReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_observed_received_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.ToTable("chunk_build_checkpoints", (string)null);
                });

            modelBuilder.Entity("SuperChat.Infrastructure.Shared.Persistence.ExtractedItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<string>("Person")
                        .HasColumnType("text")
                        .HasColumnName("person");

                    b.Property<double?>("ResolutionConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("resolution_confidence");

                    b.Property<string>("ResolutionEvidenceJson")
                        .HasColumnType("text")
                        .HasColumnName("resolution_evidence_json");

                    b.Property<string>("ResolutionKind")
                        .HasColumnType("text")
                        .HasColumnName("resolution_kind");

                    b.Property<string>("ResolutionModel")
                        .HasColumnType("text")
                        .HasColumnName("resolution_model");

                    b.Property<string>("ResolutionSource")
                        .HasColumnType("text")
                        .HasColumnName("resolution_source");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("SourceEventId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_event_id");

                    b.Property<string>("SourceRoom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_room");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ObservedAt");

                    b.ToTable("extracted_items", (string)null);
                });

            modelBuilder.Entity("SuperChat.Infrastructure.Shared.Persistence.FeedbackEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("area");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("feedback_events", (string)null);
                });

            modelBuilder.Entity("SuperChat.Infrastructure.Shared.Persistence.MeetingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MeetingJoinUrl")
                        .HasColumnType("text")
                        .HasColumnName("meeting_join_url");

                    b.Property<string>("MeetingProvider")
                        .HasColumnType("text")
                        .HasColumnName("meeting_provider");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<string>("Person")
                        .HasColumnType("text")
                        .HasColumnName("person");

                    b.Property<double?>("ResolutionConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("resolution_confidence");

                    b.Property<string>("ResolutionEvidenceJson")
                        .HasColumnType("text")
                        .HasColumnName("resolution_evidence_json");

                    b.Property<string>("ResolutionKind")
                        .HasColumnType("text")
                        .HasColumnName("resolution_kind");

                    b.Property<string>("ResolutionModel")
                        .HasColumnType("text")
                        .HasColumnName("resolution_model");

                    b.Property<string>("ResolutionSource")
                        .HasColumnType("text")
                        .HasColumnName("resolution_source");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<DateTimeOffset?>("ScheduledFor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for");

                    b.Property<string>("SourceEventId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_event_id");

                    b.Property<string>("SourceRoom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_room");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ScheduledFor");

                    b.HasIndex("UserId", "SourceEventId")
                        .IsUnique();

                    b.HasIndex("UserId", "Status", "ScheduledFor");

                    b.ToTable("meetings", (string)null);
                });

            modelBuilder.Entity("SuperChat.Infrastructure.Shared.Persistence.MeetingProjectionCheckpointEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("LastObservedChunkId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_observed_chunk_id");

                    b.Property<DateTimeOffset?>("LastObservedChunkUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_observed_chunk_updated_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.ToTable("meeting_projection_checkpoints", (string)null);
                });

            modelBuilder.Entity("SuperChat.Infrastructure.Shared.Persistence.MessageChunkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chat_id");

                    b.Property<int>("ChunkVersion")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_version");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EmbeddingVersion")
                        .HasColumnType("text")
                        .HasColumnName("embedding_version");

                    b.Property<Guid?>("FirstChatMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("first_chat_message_id");

                    b.Property<DateTimeOffset?>("IndexedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("indexed_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<Guid?>("LastChatMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_chat_message_id");

                    b.Property<int>("MessageCount")
                        .HasColumnType("integer")
                        .HasColumnName("message_count");

                    b.Property<string>("PeerId")
                        .HasColumnType("text")
                        .HasColumnName("peer_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("QdrantPointId")
                        .HasColumnType("text")
                        .HasColumnName("qdrant_point_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("ThreadId")
                        .HasColumnType("text")
                        .HasColumnName("thread_id");

                    b.Property<string>("Transport")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transport");

                    b.Property<DateTimeOffset>("TsFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts_from");

                    b.Property<DateTimeOffset>("TsTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts_to");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "TsFrom");

                    b.HasIndex("UserId", "ChatId", "TsFrom");

                    b.ToTable("message_chunks", (string)null);
                });

            modelBuilder.Entity("SuperChat.Infrastructure.Shared.Persistence.PilotInviteEntity", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("InvitedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invited_at");

                    b.Property<string>("InvitedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("invited_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.HasKey("Email");

                    b.ToTable("pilot_invites", (string)null);
                });

            modelBuilder.Entity("SuperChat.Infrastructure.Shared.Persistence.RetrievalLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CandidateCount")
                        .HasColumnType("integer")
                        .HasColumnName("candidate_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FiltersJson")
                        .HasColumnType("text")
                        .HasColumnName("filters_json");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("latency_ms");

                    b.Property<string>("ModelVersionsJson")
                        .HasColumnType("text")
                        .HasColumnName("model_versions_json");

                    b.Property<string>("QueryKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("query_kind");

                    b.Property<string>("QueryText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("query_text");

                    b.Property<string>("SelectedChunkIdsJson")
                        .HasColumnType("text")
                        .HasColumnName("selected_chunk_ids_json");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("retrieval_logs", (string)null);
                });

            modelBuilder.Entity("SuperChat.Infrastructure.Shared.Persistence.TelegramConnectionEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset?>("DevelopmentSeededAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("development_seeded_at");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.HasIndex("State");

                    b.ToTable("telegram_connections", (string)null);
                });

            modelBuilder.Entity("SuperChat.Infrastructure.Shared.Persistence.TelegramSessionEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<byte[]>("AuthKeyEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("auth_key_encrypted");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DcId")
                        .HasColumnType("integer")
                        .HasColumnName("dc_id");

                    b.Property<int>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<string>("ServerAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("server_address");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.ToTable("telegram_sessions", (string)null);
                });

            modelBuilder.Entity("SuperChat.Infrastructure.Shared.Persistence.VerificationCodeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("character varying(44)")
                        .HasColumnName("code_hash");

                    b.Property<string>("CodeSalt")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("code_salt");

                    b.Property<bool>("Consumed")
                        .IsConcurrencyToken()
                        .HasColumnType("boolean")
                        .HasColumnName("consumed");

                    b.Property<Guid?>("ConsumedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("consumed_by_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_attempts");

                    b.HasKey("Id");

                    b.HasIndex("Email", "CreatedAt");

                    b.ToTable("verification_codes", (string)null);
                });

            modelBuilder.Entity("SuperChat.Infrastructure.Shared.Persistence.WorkItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<string>("Person")
                        .HasColumnType("text")
                        .HasColumnName("person");

                    b.Property<double?>("ResolutionConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("resolution_confidence");

                    b.Property<string>("ResolutionEvidenceJson")
                        .HasColumnType("text")
                        .HasColumnName("resolution_evidence_json");

                    b.Property<string>("ResolutionKind")
                        .HasColumnType("text")
                        .HasColumnName("resolution_kind");

                    b.Property<string>("ResolutionModel")
                        .HasColumnType("text")
                        .HasColumnName("resolution_model");

                    b.Property<string>("ResolutionSource")
                        .HasColumnType("text")
                        .HasColumnName("resolution_source");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("SourceEventId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_event_id");

                    b.Property<string>("SourceRoom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_room");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DueAt");

                    b.HasIndex("UserId", "ObservedAt");

                    b.ToTable("work_items", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
