using System.Text.Json.Serialization;

namespace SuperChat.Contracts.ViewModels;

[JsonPolymorphic(TypeDiscriminatorPropertyName = "modelType")]
[JsonDerivedType(typeof(RequestWorkItemCardViewModel), "request")]
[JsonDerivedType(typeof(EventWorkItemCardViewModel), "event")]
[JsonDerivedType(typeof(ObligationWorkItemCardViewModel), "obligation")]
public record WorkItemCardViewModel(
    string Title,
    string Summary,
    string Kind,
    DateTimeOffset ObservedAt,
    DateTimeOffset? DueAt,
    string SourceRoom,
    double Confidence = 0d,
    WorkItemType? Type = null,
    WorkItemStatus? Status = null,
    WorkItemPriority Priority = WorkItemPriority.Normal,
    WorkItemOwner? Owner = null,
    WorkItemOrigin Origin = WorkItemOrigin.DetectedFromChat,
    AiReviewState ReviewState = AiReviewState.NeedsReview,
    DateTimeOffset? PlannedAt = null,
    WorkItemSource Source = WorkItemSource.Telegram,
    DateTimeOffset? UpdatedAt = null,
    bool IsOverdue = false,
    MeetingJoinProvider? MeetingProvider = null,
    Uri? MeetingJoinUrl = null);

public sealed record RequestWorkItemCardViewModel(
    string Title,
    string Summary,
    string Kind,
    DateTimeOffset ObservedAt,
    DateTimeOffset? DueAt,
    string SourceRoom,
    RequestStatus RequestStatus = RequestStatus.AwaitingResponse,
    double Confidence = 0d,
    WorkItemPriority Priority = WorkItemPriority.Normal,
    WorkItemOwner? Owner = null,
    WorkItemOrigin Origin = WorkItemOrigin.Request,
    AiReviewState ReviewState = AiReviewState.NeedsReview,
    DateTimeOffset? PlannedAt = null,
    WorkItemSource Source = WorkItemSource.Telegram,
    DateTimeOffset? UpdatedAt = null,
    bool IsOverdue = false)
    : WorkItemCardViewModel(
        Title,
        Summary,
        Kind,
        ObservedAt,
        DueAt,
        SourceRoom,
        Confidence,
        WorkItemType.Request,
        RequestStatus.ToWorkItemStatus(),
        Priority,
        Owner,
        Origin,
        ReviewState,
        PlannedAt,
        Source,
        UpdatedAt,
        IsOverdue);

public sealed record EventWorkItemCardViewModel(
    string Title,
    string Summary,
    string Kind,
    DateTimeOffset ObservedAt,
    DateTimeOffset? DueAt,
    string SourceRoom,
    EventStatus EventStatus = EventStatus.PendingConfirmation,
    double Confidence = 0d,
    WorkItemPriority Priority = WorkItemPriority.Normal,
    WorkItemOwner? Owner = null,
    WorkItemOrigin Origin = WorkItemOrigin.DetectedFromChat,
    AiReviewState ReviewState = AiReviewState.NeedsReview,
    DateTimeOffset? PlannedAt = null,
    WorkItemSource Source = WorkItemSource.Telegram,
    DateTimeOffset? UpdatedAt = null,
    bool IsOverdue = false,
    MeetingJoinProvider? MeetingProvider = null,
    Uri? MeetingJoinUrl = null)
    : WorkItemCardViewModel(
        Title,
        Summary,
        Kind,
        ObservedAt,
        DueAt,
        SourceRoom,
        Confidence,
        WorkItemType.Event,
        EventStatus.ToWorkItemStatus(),
        Priority,
        Owner,
        Origin,
        ReviewState,
        PlannedAt,
        Source,
        UpdatedAt,
        IsOverdue,
        MeetingProvider,
        MeetingJoinUrl);

public sealed record ObligationWorkItemCardViewModel(
    string Title,
    string Summary,
    string Kind,
    DateTimeOffset ObservedAt,
    DateTimeOffset? DueAt,
    string SourceRoom,
    ObligationStatus ObligationStatus = ObligationStatus.ToDo,
    double Confidence = 0d,
    WorkItemPriority Priority = WorkItemPriority.Normal,
    WorkItemOwner? Owner = null,
    WorkItemOrigin Origin = WorkItemOrigin.DetectedFromChat,
    AiReviewState ReviewState = AiReviewState.NeedsReview,
    DateTimeOffset? PlannedAt = null,
    WorkItemSource Source = WorkItemSource.Telegram,
    DateTimeOffset? UpdatedAt = null,
    bool IsOverdue = false)
    : WorkItemCardViewModel(
        Title,
        Summary,
        Kind,
        ObservedAt,
        DueAt,
        SourceRoom,
        Confidence,
        WorkItemType.Obligation,
        ObligationStatus.ToWorkItemStatus(),
        Priority,
        Owner,
        Origin,
        ReviewState,
        PlannedAt,
        Source,
        UpdatedAt,
        IsOverdue);
