using System.Text.Json.Serialization;

namespace SuperChat.Contracts.ViewModels;

[JsonPolymorphic(TypeDiscriminatorPropertyName = "modelType")]
[JsonDerivedType(typeof(RequestWorkItemCardViewModel), "request")]
[JsonDerivedType(typeof(EventWorkItemCardViewModel), "event")]
[JsonDerivedType(typeof(ActionItemWorkItemCardViewModel), "actionItem")]
public record WorkItemCardViewModel(
    string? ActionKey,
    string Title,
    string Summary,
    string Kind,
    DateTimeOffset ObservedAt,
    DateTimeOffset? DueAt,
    string SourceRoom,
    double Confidence = 0d,
    WorkItemType? Type = null,
    WorkItemStatus? Status = null,
    WorkItemPriority Priority = WorkItemPriority.Normal,
    WorkItemOwner? Owner = null,
    WorkItemOrigin Origin = WorkItemOrigin.DetectedFromChat,
    AiReviewState ReviewState = AiReviewState.NeedsReview,
    DateTimeOffset? PlannedAt = null,
    WorkItemSource Source = WorkItemSource.Telegram,
    DateTimeOffset? UpdatedAt = null,
    bool IsOverdue = false,
    MeetingJoinProvider? MeetingProvider = null,
    Uri? MeetingJoinUrl = null)
{
    public WorkItemCardViewModel(
        string Title,
        string Summary,
        string Kind,
        DateTimeOffset ObservedAt,
        DateTimeOffset? DueAt,
        string SourceRoom,
        double Confidence = 0d,
        WorkItemType? Type = null,
        WorkItemStatus? Status = null,
        WorkItemPriority Priority = WorkItemPriority.Normal,
        WorkItemOwner? Owner = null,
        WorkItemOrigin Origin = WorkItemOrigin.DetectedFromChat,
        AiReviewState ReviewState = AiReviewState.NeedsReview,
        DateTimeOffset? PlannedAt = null,
        WorkItemSource Source = WorkItemSource.Telegram,
        DateTimeOffset? UpdatedAt = null,
        bool IsOverdue = false,
        MeetingJoinProvider? MeetingProvider = null,
        Uri? MeetingJoinUrl = null)
        : this(
            null,
            Title,
            Summary,
            Kind,
            ObservedAt,
            DueAt,
            SourceRoom,
            Confidence,
            Type,
            Status,
            Priority,
            Owner,
            Origin,
            ReviewState,
            PlannedAt,
            Source,
            UpdatedAt,
            IsOverdue,
            MeetingProvider,
            MeetingJoinUrl)
    {
    }
}

public sealed record RequestWorkItemCardViewModel(
    string Title,
    string Summary,
    string Kind,
    DateTimeOffset ObservedAt,
    DateTimeOffset? DueAt,
    string SourceRoom,
    RequestStatus RequestStatus = RequestStatus.AwaitingResponse,
    double Confidence = 0d,
    WorkItemPriority Priority = WorkItemPriority.Normal,
    WorkItemOwner? Owner = null,
    WorkItemOrigin Origin = WorkItemOrigin.Request,
    AiReviewState ReviewState = AiReviewState.NeedsReview,
    DateTimeOffset? PlannedAt = null,
    WorkItemSource Source = WorkItemSource.Telegram,
    DateTimeOffset? UpdatedAt = null,
    bool IsOverdue = false)
    : WorkItemCardViewModel(
        null,
        Title,
        Summary,
        Kind,
        ObservedAt,
        DueAt,
        SourceRoom,
        Confidence,
        WorkItemType.Request,
        RequestStatus.ToWorkItemStatus(),
        Priority,
        Owner,
        Origin,
        ReviewState,
        PlannedAt,
        Source,
        UpdatedAt,
        IsOverdue);

public sealed record EventWorkItemCardViewModel(
    string Title,
    string Summary,
    string Kind,
    DateTimeOffset ObservedAt,
    DateTimeOffset? DueAt,
    string SourceRoom,
    EventStatus EventStatus = EventStatus.PendingConfirmation,
    double Confidence = 0d,
    WorkItemPriority Priority = WorkItemPriority.Normal,
    WorkItemOwner? Owner = null,
    WorkItemOrigin Origin = WorkItemOrigin.DetectedFromChat,
    AiReviewState ReviewState = AiReviewState.NeedsReview,
    DateTimeOffset? PlannedAt = null,
    WorkItemSource Source = WorkItemSource.Telegram,
    DateTimeOffset? UpdatedAt = null,
    bool IsOverdue = false,
    MeetingJoinProvider? MeetingProvider = null,
    Uri? MeetingJoinUrl = null)
    : WorkItemCardViewModel(
        null,
        Title,
        Summary,
        Kind,
        ObservedAt,
        DueAt,
        SourceRoom,
        Confidence,
        WorkItemType.Event,
        EventStatus.ToWorkItemStatus(),
        Priority,
        Owner,
        Origin,
        ReviewState,
        PlannedAt,
        Source,
        UpdatedAt,
        IsOverdue,
        MeetingProvider,
        MeetingJoinUrl);

public sealed record ActionItemWorkItemCardViewModel(
    string Title,
    string Summary,
    string Kind,
    DateTimeOffset ObservedAt,
    DateTimeOffset? DueAt,
    string SourceRoom,
    ActionItemStatus ActionItemStatus = ActionItemStatus.ToDo,
    double Confidence = 0d,
    WorkItemPriority Priority = WorkItemPriority.Normal,
    WorkItemOwner? Owner = null,
    WorkItemOrigin Origin = WorkItemOrigin.DetectedFromChat,
    AiReviewState ReviewState = AiReviewState.NeedsReview,
    DateTimeOffset? PlannedAt = null,
    WorkItemSource Source = WorkItemSource.Telegram,
    DateTimeOffset? UpdatedAt = null,
    bool IsOverdue = false)
    : WorkItemCardViewModel(
        null,
        Title,
        Summary,
        Kind,
        ObservedAt,
        DueAt,
        SourceRoom,
        Confidence,
        WorkItemType.ActionItem,
        ActionItemStatus.ToWorkItemStatus(),
        Priority,
        Owner,
        Origin,
        ReviewState,
        PlannedAt,
        Source,
        UpdatedAt,
        IsOverdue);
