homeserver:
  address: http://synapse:8008
  domain: matrix.localhost
  software: standard

appservice:
  address: http://mautrix-telegram:29317
  hostname: 0.0.0.0
  port: 29317
  id: telegram
  bot:
    username: telegrambot
    displayname: Telegram Bridge
  as_token: dev-mautrix-as-token
  hs_token: dev-mautrix-hs-token
  database: postgres://postgres:postgres@postgres/mautrix_telegram?sslmode=disable

telegram:
  api_id: 123456
  api_hash: replace-me

bridge:
  permissions:
    '*': relaybot
    matrix.localhost: user
  relaybot:
    enabled: false
  backfill:
    enabled: false
  sync_direct_chats: true
