from pathlib import Path


PORTAL_TARGET = Path("/usr/lib/python3.12/site-packages/mautrix_telegram/portal.py")
PORTAL_OLD = """        self.log.debug(f"Iterating messages through {source.tgid} with {limit=}, {minmax}")\n        delay_warn_handle = self.loop.call_later(\n            5 * 60, lambda: self.log.warning("Iterating messages is taking long")\n        )\n        # Iterate messages newest to oldest and collect the results\n        async for msg in client.iter_messages(entity, limit=limit, **minmax):\n            message_count += 1\n            if message_count == 1:\n                self.log.debug(f"Backfill iter: got first message {msg.id}")\n            elif message_count % 50 == 0:\n                self.log.debug(f"Backfill iter: got {message_count} messages so far (at {msg.id})")\n            if (forward and msg.id <= anchor_id) or (not forward and msg.id >= anchor_id):\n                continue\n            elif isinstance(msg, MessageService):\n                # TODO some service messages can be backfilled\n                continue\n            if not lowest_id or msg.id < lowest_id:\n                lowest_id = msg.id\n            if not first_id_found:\n                first_id = msg.id\n                first_id_found = True\n\n            converted, intent = await self._convert_batch_msg(source, client, msg)\n            if converted is None:\n                continue\n            d_event_id = None\n            if self.bridge.homeserver_software.is_hungry:\n                d_event_id = self._msg_conv.deterministic_event_id(tg_space, msg.id)\n            events.append(await self._wrap_batch_msg(intent, msg, converted, event_id=d_event_id))\n            intents.append(intent)\n            metas.append(msg)\n            if converted.caption:\n                events.append(await self._wrap_batch_msg(intent, msg, converted, caption=True))\n                intents.append(intent)\n                metas.append(None)\n        delay_warn_handle.cancel()\n"""
PORTAL_NEW = """        self.log.debug(f"Iterating messages through {source.tgid} with {limit=}, {minmax}")\n        self.log.debug(\n            f"Starting Telegram history fetch through {source.tgid} "\n            f"for {self.tgid} (forward={forward}, anchor_id={anchor_id}, {limit=}, {minmax})"\n        )\n        delay_warn_handle = self.loop.call_later(\n            5 * 60, lambda: self.log.warning("Iterating messages is taking long")\n        )\n        iterator = client.iter_messages(entity, limit=limit, **minmax)\n        try:\n            # Iterate messages newest to oldest and collect the results.\n            while True:\n                try:\n                    msg = await asyncio.wait_for(iterator.__anext__(), timeout=60)\n                except StopAsyncIteration:\n                    break\n                except asyncio.TimeoutError:\n                    self.log.warning(\n                        f"Timed out waiting for Telegram history through {source.tgid} "\n                        f"for {self.tgid} after 60s (forward={forward}, anchor_id={anchor_id}, {limit=}, {minmax})"\n                    )\n                    break\n                message_count += 1\n                if message_count == 1:\n                    self.log.debug(f"Backfill iter: got first message {msg.id}")\n                elif message_count % 50 == 0:\n                    self.log.debug(f"Backfill iter: got {message_count} messages so far (at {msg.id})")\n                if (forward and msg.id <= anchor_id) or (not forward and msg.id >= anchor_id):\n                    continue\n                elif isinstance(msg, MessageService):\n                    # TODO some service messages can be backfilled\n                    continue\n                if not lowest_id or msg.id < lowest_id:\n                    lowest_id = msg.id\n                if not first_id_found:\n                    first_id = msg.id\n                    first_id_found = True\n\n                converted, intent = await self._convert_batch_msg(source, client, msg)\n                if converted is None:\n                    continue\n                d_event_id = None\n                if self.bridge.homeserver_software.is_hungry:\n                    d_event_id = self._msg_conv.deterministic_event_id(tg_space, msg.id)\n                events.append(await self._wrap_batch_msg(intent, msg, converted, event_id=d_event_id))\n                intents.append(intent)\n                metas.append(msg)\n                if converted.caption:\n                    events.append(await self._wrap_batch_msg(intent, msg, converted, caption=True))\n                    intents.append(intent)\n                    metas.append(None)\n        finally:\n            delay_warn_handle.cancel()\n        self.log.debug(\n            f"Telegram history fetch finished through {source.tgid} "\n            f"for {self.tgid} with {message_count} raw messages"\n        )\n"""

USER_TARGET = Path("/usr/lib/python3.12/site-packages/mautrix_telegram/user.py")
USER_OLD = """        async for dialog in self.client.iter_dialogs(\n            limit=update_limit, ignore_migrated=True, archived=False\n        ):\n            entity = dialog.entity\n            if isinstance(entity, ChatForbidden):\n                self.log.warning(f\"Ignoring forbidden chat {entity} while syncing\")\n                continue\n            elif isinstance(entity, Chat) and (entity.deactivated or entity.left):\n                self.log.warning(f\"Ignoring deactivated or left chat {entity} while syncing\")\n                continue\n            elif isinstance(entity, TLUser) and not self.config[\"bridge.sync_direct_chats\"]:\n                self.log.trace(f\"Ignoring user {entity.id} while syncing\")\n                continue\n            portal = await po.Portal.get_by_entity(entity, tg_receiver=self.tgid)\n            new_portal_cache[portal.tgid_full] = portal\n            should_create = not create_limit or index < create_limit\n            coro = self._sync_dialog(\n                portal=portal,\n                dialog=dialog,\n                puppet=puppet,\n                should_create=should_create,\n            )\n            creators.append(asyncio.create_task(coro))\n            index += 1\n"""
USER_NEW = """        dialog_iterator = self.client.iter_dialogs(\n            limit=update_limit, ignore_migrated=True, archived=False\n        )\n        self.log.debug(\n            f\"Starting dialog iteration for {self.mxid} \"\n            f\"({update_limit=}, {create_limit=})\"\n        )\n        while True:\n            try:\n                dialog = await asyncio.wait_for(dialog_iterator.__anext__(), timeout=60)\n            except StopAsyncIteration:\n                break\n            except asyncio.TimeoutError:\n                self.log.warning(\n                    f\"Timed out while iterating dialogs for {self.mxid} after 60s \"\n                    f\"(processed={index}, {update_limit=}, {create_limit=})\"\n                )\n                break\n            entity = dialog.entity\n            if isinstance(entity, ChatForbidden):\n                self.log.warning(f\"Ignoring forbidden chat {entity} while syncing\")\n                continue\n            elif isinstance(entity, Chat) and (entity.deactivated or entity.left):\n                self.log.warning(f\"Ignoring deactivated or left chat {entity} while syncing\")\n                continue\n            elif isinstance(entity, TLUser) and not self.config[\"bridge.sync_direct_chats\"]:\n                self.log.trace(f\"Ignoring user {entity.id} while syncing\")\n                continue\n            portal = await po.Portal.get_by_entity(entity, tg_receiver=self.tgid)\n            new_portal_cache[portal.tgid_full] = portal\n            should_create = not create_limit or index < create_limit\n            coro = self._sync_dialog(\n                portal=portal,\n                dialog=dialog,\n                puppet=puppet,\n                should_create=should_create,\n            )\n            creators.append(asyncio.create_task(coro))\n            index += 1\n        self.log.debug(f\"Dialog iteration finished for {self.mxid} with {index} dialogs\")\n"""


def replace_once(path: Path, old: str, new: str) -> None:
    text = path.read_text()
    if old not in text:
        raise SystemExit(f"Target snippet not found in {path}")

    path.write_text(text.replace(old, new, 1))


def main() -> None:
    replace_once(PORTAL_TARGET, PORTAL_OLD, PORTAL_NEW)
    replace_once(USER_TARGET, USER_OLD, USER_NEW)


if __name__ == "__main__":
    main()
